apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-app-cronjob
spec:
  schedule: "0 11 * * 1,3-5"  # At 11:00 on Monday, Wednesday, Thursday, and Friday
  jobTemplate:            # Template for the job to be run
    spec:
      template:
        spec:
          nodeSelector:
            "kubernetes.io/os": windows  # Ensure the job runs on a Windows node
          containers:
          - name: my-app
            image: your-registry-name.azurecr.io/my-app:latest  # Container image to use
            resources:
              requests:
                memory: "48Gi"  # Memory request for the container
                cpu: "12"       # CPU request for the container
            volumeMounts:
            - name: my-volume
              mountPath: "/data"  # Mount path for the volume inside the container
          volumes:
          - name: my-volume
            persistentVolumeClaim:
              claimName: azurefile  # PVC that the CronJob will use
          restartPolicy: OnFailure  # Job restart policy
